name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:

  train-test-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python -m src.train

      - name: Check Accuracy
        run: |
          python check_accuracy.py

      - name: Run Tests
        run: |
          pytest

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fashion-mnist-model
          path: models/fashion_mnist.pth

      - name: Upload Metrics
        uses: actions/upload-artifact@v4
        with:
          name: training-metrics
          path: metrics.json

      - name: Deploy To Render
        run: |
          curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}